Solution.Web.CNF/Controllers/ChargeImportController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Solution.Core;
using Solution.Core.Models.CNF.Dto;
using Solution.Core.Models.Common.Dto;
using Solution.Web.CNF.Services.IServices;

namespace Solution.Web.CNF.Controllers
{
	public class ChargeImportController : Controller
	{
		private readonly IUnitOfService _Service;
		private readonly IHttpContextAccessor _httpContextAccessor;
		private string controllerName;
		private string route = "Charge";
		private string flag = "Import";

		public ChargeImportController(IUnitOfService service, IHttpContextAccessor httpContextAccessor)
		{
			_Service = service;
			_httpContextAccessor = httpContextAccessor;
			controllerName = _httpContextAccessor.HttpContext.Request.RouteValues["controller"].ToString();
		}
		public async Task<IActionResult> Index()
		{
			if (!Request.Cookies.ContainsKey("ComId"))
			{
				return RedirectToAction(nameof(Index), "Home");
			}
			//var ComId = Request.Cookies["ComId"];
			//var UserId = Request.Cookies["UserId"];

			//List<ChargeDto> list = new();
			//var response = await _Service.Charges.GetAllAsync(ComId, UserId, route);
			//if (response != null && response.IsSuccess)
			//{
			//	list = JsonConvert.DeserializeObject<List<ChargeDto>>(Convert.ToString(response.Result)).Where(x=>x.Flag==flag).ToList();
			//}
			return View();
		}

		// GET: ChargesController/Details/5
		public async Task<IActionResult> Details(string id)
		{
			var ComId = Request.Cookies["ComId"];
			var UserId = Request.Cookies["UserId"];
			var model = await _Service.Charges.GetByIdAsync(SD.CNFAPIBase, id, ComId, UserId, route);
			if (model == null)
			{
				return NotFound();
			}
			return View(model);
		}

		// GET: ChargesController/Create
		public async Task<ActionResult> Create()
		{
			var ComId = Request.Cookies["ComId"];
			var UserId = Request.Cookies["UserId"];

			List<CommonDataDto> DepartmentList = new();
			var response = await _Service.CommonDatas.GetAllAsync(SD.HRAPIBase, ComId, UserId, "CommonData");
			if (response != null && response.IsSuccess)
			{
				DepartmentList = JsonConvert.DeserializeObject<List<CommonDataDto>>(Convert.ToString(response.Result)).Where(x => x.CommonType == "Import Dept").ToList();
			}
			ViewBag.DepartmentList = new SelectList(DepartmentList, "CommonName", "CommonName");

			CreateChargeDto model = new CreateChargeDto()
			{
				Rate = 0,
				Department = "Custom"
			};
			return View(model);
		}

		// POST: ChargesController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(ChargeDto model)
		{
			string ComId = Request.Cookies["ComId"].ToString();
			string UserId = Request.Cookies["UserId"].ToString();
			ResponseDto response = new();
			if (ModelState.IsValid)
			{
				model.ComId = ComId;
				model.Flag = flag;
				response = await _Service.Charges.CreateAsync(SD.CNFAPIBase, model, ComId, UserId, route);
				if (response != null && response.IsSuccess)
				{
					TempData["Success"] = $"{controllerName} created successfully.";
					return RedirectToAction(nameof(Index));
				}
			}
			List<CommonDataDto> DepartmentList = new();
			response = await _Service.CommonDatas.GetAllAsync(SD.HRAPIBase, ComId, UserId, "CommonData");
			if (response != null && response.IsSuccess)
			{
				DepartmentList = JsonConvert.DeserializeObject<List<CommonDataDto>>(Convert.ToString(response.Result)).Where(x => x.CommonType == "Import Dept").ToList();
			}
			ViewBag.DepartmentList = new SelectList(DepartmentList, "CommonName", "CommonName");
			return View(model);
		}

		// GET: ChargesController/Edit/5
		public async Task<IActionResult> Edit(string id)
		{
			var ComId = Request.Cookies["ComId"].ToString();
			string UserId = Request.Cookies["UserId"].ToString();

			var response = await _Service.Charges.GetByIdAsync(SD.CNFAPIBase, id, ComId, UserId, route);
			if (response != null && response.IsSuccess)
			{
				ChargeDto model = JsonConvert.DeserializeObject<ChargeDto>(Convert.ToString(response.Result));
				
				List<CommonDataDto> DepartmentList = new();
				response = await _Service.CommonDatas.GetAllAsync(SD.HRAPIBase, ComId, UserId, "CommonData");
				if (response != null && response.IsSuccess)
				{
					DepartmentList = JsonConvert.DeserializeObject<List<CommonDataDto>>(Convert.ToString(response.Result)).Where(x => x.CommonType == "Import Dept").ToList();
				}
				ViewBag.DepartmentList = new SelectList(DepartmentList, "CommonName", "CommonName");

				return View(model);
			}
			return NotFound();
		}

		// POST: ChargesController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(ChargeDto model)
		{
			var ComId = Request.Cookies["ComId"].ToString();
			string UserId = Request.Cookies["UserId"].ToString();

			ResponseDto response = new();
			if (ModelState.IsValid)
			{
				model.ComId = ComId;
				model.Flag = flag;
				response = await _Service.Charges.UpdateAsync(SD.CNFAPIBase, model, ComId, UserId, route);
				if (response != null && response.IsSuccess)
				{
					TempData["Success"] = $"{controllerName} updated successfully.";
					return RedirectToAction(nameof(Index));
				}
			}
			List<CommonDataDto> DepartmentList = new();
			response = await _Service.CommonDatas.GetAllAsync(SD.HRAPIBase, ComId, UserId, "CommonData");
			if (response != null && response.IsSuccess)
			{
				DepartmentList = JsonConvert.DeserializeObject<List<CommonDataDto>>(Convert.ToString(response.Result)).Where(x => x.CommonType == "Import Dept").ToList();
			}
			ViewBag.DepartmentList = new SelectList(DepartmentList, "CommonName", "CommonName");

			return View(model);
		}

		// GET: ChargesController/Delete/5
		public async Task<IActionResult> Delete(string id)
		{
			var ComId = Request.Cookies["ComId"];
			string UserId = Request.Cookies["UserId"].ToString();

			var response = await _Service.Charges.GetByIdAsync(SD.CNFAPIBase, id, ComId, UserId, route);
			if (response != null && response.IsSuccess)
			{
				ChargeDto model = JsonConvert.DeserializeObject<ChargeDto>(Convert.ToString(response.Result));

				List<CommonDataDto> DepartmentList = new();
				response = await _Service.CommonDatas.GetAllAsync(SD.HRAPIBase, ComId, UserId, "CommonData");
				if (response != null && response.IsSuccess)
				{
					DepartmentList = JsonConvert.DeserializeObject<List<CommonDataDto>>(Convert.ToString(response.Result)).Where(x => x.CommonType == "Import Dept").ToList();
				}
				ViewBag.DepartmentList = new SelectList(DepartmentList, "CommonName", "CommonName");

				return View(model);
			}
			return NotFound();
		}

		// POST: ChargesController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Delete(ChargeDto model)
		{
			var ComId = Request.Cookies["ComId"];
			string UserId = Request.Cookies["UserId"].ToString();

			var response = await _Service.Charges.DeleteAsync(SD.CNFAPIBase, model.Id, ComId, UserId, route);
			if (response.IsSuccess)
			{
				TempData["Success"] = $"{controllerName} deleted successfully.";
				return RedirectToAction(nameof(Index));
			}

			List<CommonDataDto> DepartmentList = new();
			response = await _Service.CommonDatas.GetAllAsync(SD.HRAPIBase, ComId, UserId, "CommonData");
			if (response != null && response.IsSuccess)
			{
				DepartmentList = JsonConvert.DeserializeObject<List<CommonDataDto>>(Convert.ToString(response.Result)).Where(x => x.CommonType == "Import Dept").ToList();
			}
			ViewBag.DepartmentList = new SelectList(DepartmentList, "CommonName", "CommonName");

			return View(model);
		}

		[HttpGet]
		public IActionResult GetAll()
		{
			var ComId = Request.Cookies["ComId"];
			var UserId = Request.Cookies["UserId"];

			List<ChargeDto> list = new();
			var response = _Service.Charges.GetAllAsync(SD.CNFAPIBase, ComId, UserId, route).Result;
			if (response != null && response.IsSuccess)
			{
				list = JsonConvert.DeserializeObject<List<ChargeDto>>(Convert.ToString(response.Result)).Where(x => x.Flag == flag).ToList();
			}
			return Json(new { Success = 1, error = false, data = list });
		}
	}
}

Solution.Web.CNF/Controllers/ClientImportController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Solution.Core;
using Solution.Core.Models.CNF.Dto;
using Solution.Web.CNF.Services.IServices;

namespace Solution.Web.CNF.Controllers
{
	public class ClientImportController : Controller
	{
		private readonly IUnitOfService _Service;
		private readonly IHttpContextAccessor _httpContextAccessor;
		private string controllerName;
		private string route = "Client";
		private string flag = "Import";

		public ClientImportController(IUnitOfService service, IHttpContextAccessor httpContextAccessor)
		{
			_Service = service;
			_httpContextAccessor = httpContextAccessor;
			controllerName = _httpContextAccessor.HttpContext.Request.RouteValues["controller"].ToString();
		}
		public async Task<IActionResult> Index()
		{
			if (!Request.Cookies.ContainsKey("ComId"))
			{
				return RedirectToAction(nameof(Index), "Home");
			}
			return View();
		}

		// GET: ClientsController/Details/5
		public async Task<IActionResult> Details(string id)
		{
			var ComId = Request.Cookies["ComId"];
			var UserId = Request.Cookies["UserId"];
			var model = await _Service.Clients.GetByIdAsync(SD.CNFAPIBase, id, ComId, UserId, route);
			if (model == null)
			{
				return NotFound();
			}
			return View(model);
		}

		// GET: ClientsController/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: ClientsController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(ClientDto model)
		{
			if (ModelState.IsValid)
			{
				string ComId = Request.Cookies["ComId"].ToString();
				string UserId = Request.Cookies["UserId"].ToString();

				model.ComId = ComId;
				model.Flag = flag;
				var response = await _Service.Clients.CreateAsync(SD.CNFAPIBase, model, ComId, UserId, route);
				if (response != null && response.IsSuccess)
				{
					TempData["Success"] = $"{controllerName} created successfully.";
					return RedirectToAction(nameof(Index));
				}
			}
			return View(model);
		}

		// GET: ClientsController/Edit/5
		public async Task<IActionResult> Edit(string id)
		{
			var ComId = Request.Cookies["ComId"].ToString();
			string UserId = Request.Cookies["UserId"].ToString();

			var response = await _Service.Clients.GetByIdAsync(SD.CNFAPIBase, id, ComId, UserId, route);
			if (response != null && response.IsSuccess)
			{
				ClientDto model = JsonConvert.DeserializeObject<ClientDto>(Convert.ToString(response.Result));
				return View(model);
			}
			return NotFound();
		}

		// POST: ClientsController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(ClientDto model)
		{
			if (ModelState.IsValid)
			{
				var ComId = Request.Cookies["ComId"].ToString();
				string UserId = Request.Cookies["UserId"].ToString();

				model.ComId = ComId;
				model.Flag = flag;
				var response = await _Service.Clients.UpdateAsync(SD.CNFAPIBase, model, ComId, UserId, route);
				if (response != null && response.IsSuccess)
				{
					TempData["Success"] = $"{controllerName} updated successfully.";
					return RedirectToAction(nameof(Index));
				}
			}
			return View(model);
		}

		// GET: ClientsController/Delete/5
		public async Task<IActionResult> Delete(string id)
		{
			var ComId = Request.Cookies["ComId"];
			string UserId = Request.Cookies["UserId"].ToString();

			var response = await _Service.Clients.GetByIdAsync(SD.CNFAPIBase, id, ComId, UserId, route);
			if (response != null && response.IsSuccess)
			{
				ClientDto model = JsonConvert.DeserializeObject<ClientDto>(Convert.ToString(response.Result));
				return View(model);
			}
			return NotFound();
		}

		// POST: ClientsController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Delete(ClientDto model)
		{
			var ComId = Request.Cookies["ComId"];
			string UserId = Request.Cookies["UserId"].ToString();

			var response = await _Service.Clients.DeleteAsync(SD.CNFAPIBase, model.Id, ComId, UserId, route);
			if (response.IsSuccess)
			{
				TempData["Success"] = $"{controllerName} deleted successfully.";
				return RedirectToAction(nameof(Index));
			}
			return View(model);
		}
		[HttpGet]
		public IActionResult GetAll()
		{
			var ComId = Request.Cookies["ComId"];
			var UserId = Request.Cookies["UserId"];

			List<ClientDto> list = new();
			var response = _Service.Clients.GetAllAsync(SD.CNFAPIBase, ComId, UserId, route).Result;
			if (response != null && response.IsSuccess)
			{
				list = JsonConvert.DeserializeObject<List<ClientDto>>(Convert.ToString(response.Result)).Where(x=>x.Flag==flag).ToList();
			}
			return Json(new { Success = 1, error = false, data = list });

		}
	}
}

Solution.Web.CNF/Views/Shared/_CompanyDropdown.cshtml
@using Newtonsoft.Json;
@using Solution.Core.Models.Common.Dto;

<div class="dropdown">
	<button class="btn btn-secondary dropdown-toggle" type="button" id="companyDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		@if (Context.Request.Cookies.ContainsKey("ComName"))
		{
			@Context.Request.Cookies["ComName"].ToString()
		}
		else
		{
			<span>Select a company</span>
		}
	</button>
	<div class="dropdown-menu" aria-labelledby="companyDropdown">
		@if (Context.Request.Cookies.ContainsKey("Companies"))
		{
			var Companies = JsonConvert.DeserializeObject<IEnumerable<CompanyDto>>(Context.Request.Cookies["Companies"]);
			foreach (var company in Companies)
			{
				<a class="dropdown-item" href="#" onclick="selectCompany('@company.Id', '@company.ComName')">@company.ComName</a>
			}
		}
	</div>
</div>

<script>
	function selectCompany(ComId, ComName) {
		var date = new Date();
		var days = 7;
		date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
		var expires = "; expires=" + date.toUTCString();
		var path = "; path=/";

		document.getElementById("companyDropdown").innerText = ComName;
		document.cookie = "ComId=" + ComId + expires + path;
		document.cookie = "ComName=" + ComName + expires + path;

		// Refresh the page
		location.reload();
	}
</script>

Solution.Web.CNF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Solution.Web.CNF</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
	<link href="~/lib/tabulator/dist/css/tabulator.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Solution.Web.CNF.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Solution.Web.CNF</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						@*<li class="nav-item">
						<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>*@
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Buyer" asp-action="Index">Buyer</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Charge" asp-action="Index">Charge (Export)</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="ChargeImport" asp-action="Index">Charge (Import)</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Client (Export)</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="ClientImport" asp-action="Index">Client (Import)</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Depot" asp-action="Index">Depot</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Exchange" asp-action="Index">Exchange (Export)</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="ExchangeImport" asp-action="Index">Exchange (Import)</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Exporter" asp-action="Index">Exporter</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Forwarder" asp-action="Index">Forwarder</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Importer" asp-action="Index">Importer</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Supplier" asp-action="Index">Supplier</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Agent" asp-action="Index">Agent</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Commissioner" asp-action="Index">Commissioner</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Bank" asp-action="Index">Bank</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="BankAccount" asp-action="Index">Bank Account</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="CarryingContractor" asp-action="Index">Carrying Contractor</a>
						</li>
					</ul>
					@await Html.PartialAsync("_CompanyDropdown")
				</div>
			</div>
		</nav>
	</header>
	<div class="container-fluid">
		<main role="main" class="pb-3">
			<div class="row">
				<div class="col-2">
					<ul class="sidebar-menu">
						<li class="treeview">
							<a href="#">
								<i class="fa fa-share"></i> <span>Multilevel</span>
								<span class="pull-right-container">
									<i class="fa fa-angle-left pull-right"></i>
								</span>
							</a>
							<ul class="treeview-menu">
								<li>
									<a href="#">
										<i class="fa fa-circle-o"></i> Level One
										<span class="pull-right-container">
											<i class="fa fa-angle-left pull-right"></i>
										</span>
									</a>
									<ul class="treeview-menu">
										<li>
											<a href="#">
												<i class="fa fa-circle-o"></i> Level Two
												<span class="pull-right-container">
													<i class="fa fa-angle-left pull-right"></i>
												</span>
											</a>
											<ul class="treeview-menu">
												<li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
											</ul>
										</li>
									</ul>
								</li>
							</ul>
						</li>
					</ul>
				</div>
				<div class="col-10">
					@RenderBody()
				</div>
			</div>

			@*@RenderBody()*@
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - Solution.Web.CNF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script type="text/javascript" src="https://unpkg.com/tabulator-tables@5.5.2/dist/js/tabulator.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/font-awesome/js/all.min.js"></script>
	<script src="~/lib/tabulator/dist/js/tabulator.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Solution.Web.CNF/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["Success"]')
	</script>
}
@if (TempData["Error"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.error('@TempData["Error"]')
	</script>
}